# Generated by Django 4.2.6 on 2023-10-29 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('hashed_password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crn', models.CharField(max_length=50, unique=True)),
                ('course_name', models.CharField(max_length=255)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.professor')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceSystemRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facial_encoding_file', models.BinaryField()),
                ('qr_code_file', models.BinaryField()),
                ('registered_for_facial', models.BooleanField(default=False)),
                ('registered_for_qr', models.BooleanField(default=False)),
                ('class_crn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.class', to_field='crn')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.student')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_email', models.EmailField(max_length=255)),
                ('attendance_date', models.DateField()),
                ('attendance_time', models.TimeField()),
                ('method', models.CharField(choices=[('Facial Recognition', 'Facial Recognition'), ('QR Code', 'QR Code')], max_length=50)),
                ('class_crn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.class', to_field='crn')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.student')),
            ],
        ),
    ]
